text = """ REMOVAL OF EXISTING TOPS, BRACKETS, SUPPORTS, CARPENTRY WORK, APPLIANCE PLACEMENT, PLUMBING & ELECTRICAL HOOKUP, OR EQUIPMENT & OPERATOR TO LIFT 
COUNTERTOPS FOR UPPER LEVEL INSTALLATIONS. CUSTOMER MUST ADVISE IF AREA OF INSTALLATION REQUIRES ACCESS VIA STAIRS / STEPS. FENCO'S COMPETITIVE PRICES 
ARE ACHEIVED THROUGH A BALANCE OF LAYOUT DESIGN AND MAXIMIZING MATERIAL YIELDS. CUSTOMER SPECIFIED SEAM LOCATIONS, LAYOUT DESIGN, AND/OR SPECIAL SLAB 
SELECTIONS MAY IMPACT MATERIAL YIELDS AND INCREASE COSTS RESULTING IN ADDITIONAL CHARGES."""

text = text.title()

print(text)